### ISSUE TITLE
Switch Maps API from v1 to v2

### ISSUE THREAD

**Issue by icarapovic** [android-rcs/rcsjta#140]
The core uses some old Maps APIs that cause problem while trying to build. 
For example, com.google.android.maps.GeoPoint should be replaced with com.google.android.gms.maps.model.LatLng.

**Comment by yplo6403** [comment]
The problem here is that Google Maps Android v1 API is deprecated so you cannot get new API key. But the current Reference Implementation (having a valid key for maps v1) is running correctly even for Lollipop. There is no implicit intents involved in the current RI.
However we agree that an enhancement is required to replace Google maps API v1 by v2.

**Comment by yplo6403** [comment]
Migration from Google maps API v1 to v2 has been implemented and pushed in the integration branch.
RI APK is available at the following link: https://github.com/android-rcs/rcsjta.build/tree/integration

**Comment by icarapovic** [comment]
Great job, and very fast also. Closing the issue.
