### ISSUE TITLE
Installing RCS_RI files - Install failed missing shared library

### ISSUE THREAD

**Issue by adriancallplus** [android-rcs/rcsjta#145]
Hi
Just downloaded RCS files that were updated today and have a failure when installing RCS_RI.apk – missing shared library as shown in screenshot below.  Hence interested to find out what may be missing? i.e. what dependencies are there when using RCS. Is there an easy way to check what android thinks is missing.
FYI I am using AOSP 5.1.1 r9  as the test platform.

![installfailurercs_ri](https://cloud.githubusercontent.com/assets/14890257/10165199/d492f5c2-66b5-11e5-9259-8808662f71aa.png)

**Comment by yplo6403** [comment]
This is a bug we never experienced. Do you reproduce with the latest nightly build ?
I assume that during the period we tested the APK publication script on github, we launched the script manually without checking if APK was successfully built. Now those tasks are performed automatically and sequentially by the Jenkins server so that a SDK cannot be published if APK build failed.

**Comment by adriancallplus** [comment]
I downloaded the build dated 9th Oct and it installs fine on Nexus 5 (bld LRX210) but on AOSP on HammerHead (bld 5.1.1 LMY481); a minimal system used for testing. It has the same Missing shared library error message - so interested if there is a list of dependencies that I can check.

Thanks

**Comment by adriancallplus** [comment]
Sorry didn't mean to close  - finger trouble!!

**Comment by jmauffret** [comment]
The installation failed because the Google Maps library is not installed in your device (may be because you have built your own AOSP release). Similar error described at http://stackoverflow.com/questions/1113088/install-failed-missing-shared-library-error-in-android
And RI uses GoogleMaps library for geoloc info and display.
With an official Nexus5 devices it works (release built by Google).

**Comment by adriancallplus** [comment]
Thanks - all resolved and for those interested, here is a link to a blog describing how to resolve - http://sdgsystems.com/blog/installing-google-maps-framework-aosp-android

Also need to ensure that listed as a dependency for testing
