### ISSUE TITLE
HTTP File transfer Upload : IncompatibleClassChangeError exception upon thumbnail creation

### ISSUE THREAD

**Issue by marcbailly** [android-rcs/rcsjta#149]
An erros is encountered on the RI on File upload: when requesting a thumbnail, after pressing the upload button, the applicaton freezes and then it is displayed: Unfortunately, RCS services has stopped.
Note: when no thumbnail is requested, this is working well.

**Comment by yplo6403** [comment]
Please provide more detailed information: logcat trace and if usefull also wireshark trace.

**Comment by yplo6403** [comment]
[log-thumbnail.txt](https://github.com/android-rcs/rcsjta/files/7679/log-thumbnail.txt)
As the problem is against the core and concerns the thumbnail creation, I rename the issue.

**Comment by MurthyVadapalli** [comment]
Hi,
This error has been thrown as com.gsma.rcs.core.content.MmContent.closeFile() was not able to close
CloseableUtils.tryToClose(mPfd) .
Where mPfd  is basically of type : android.os.ParcelFileDescriptor  ,  which do implement java.io.Closeable.

So this means that there has been an issue with  library re-compilation or the Client (APK)  has been built with an old version of the library   but has  runned on a new one.


Please see below description as the cause to have java.lang.IncompatibleClassChangeError (in general) : 
"This is a complete list of changes in Java library API that may cause clients built with an old version of the library to throw java.lang.IncompatibleClassChangeError if they run on a new one (i.e. breaking BC):
- Non-final field become static,
- Non-constant field become non-static,
- Class become interface,
- Interface become class,

If you add a new field to class/interface (or add new super-class/super-interface) then a static field from a super-interface of a client class C may hide an added field (with the same name) inherited from the super-class of C (very rare case).

Note: There are many other exceptions caused by other incompatible changes: NoSuchFieldError, NoSuchMethodError, IllegalAccessError, InstantiationError, VerifyError, NoClassDefFoundError and AbstractMethodError.



Can you please confirm this is not the case here ?

Regards
Murthy

**Comment by yplo6403** [comment]
I couldn’t  reproduce the bug with the APK available on the Github web site : rcsjta_sdk_20151005-044316.zip
It was generated this morning at 4:43:16. Is it this SDK that you used for testing ? 
BTW: mention the SDK’s date in future issue description.

**Comment by yplo6403** [comment]
The bug is reproduced with a Samsung GT-19100 Version Android 4.0.3 (Ice Scream Sandwich API level 15). Then it is not a problem of generation of the core APK by our Jenkins server (the one used to publish on github) .
Fix proposed is to remove usage of ParcelFileDescriptor object since it is not implementing the closable interface for some devices.

commit d6a4589159c51a9044550e20265292d6c32a6d85
Author: yplo6403 <philippe.lemordant@orange.com>
Date:   Wed Oct 7 09:45:39 2015 +0200

    Fixes issue 149: HTTP File transfer Upload : IncompatibleClassChangeError exception upon thumbnail creation
    - Remove the ParcelFileDescriptor instance which is not closeable for some devices (Samsung GT-I9100 android version 4.0.3 ICS).
    Use instead a more standard method to create a BufferedOutputStream using a File instance.
