### ISSUE TITLE
[RI] Evolution for multimedia streaming session test

### ISSUE THREAD

**Issue by marcbailly** [android-rcs/rcsjta#171]
With the current implementation of the RI for the multimedia streaming session, the users needs to press several times the send button on both devices to make the test work. And if the button is only pressed on only one of the devices, this is not working when devices are behind a NAT (which is often the case). This is due to some NAT traversal meschanismes for UDP packet ensured at the IMS level where the network needs to received at least one packet from the device to reuse the opened binding to be able to route RTP data to the device.
An interesting evolution would be to update the RI to automatically send RTP packet: one packet per seconds for example. This would be really more simple with that to test this feature.
(note: this point was discussed with Philippe).
thx

Marc

**Comment by jmauffret** [comment]
Hi,

Instead of doing this Dummy RTP packet generator in the RI app side, it s better to implement it in the RCS stack side as we do for the VSh service. And the GSMA spec should be also updated in this case.
Or each third party app will have to do it.

BR
JM

Envoyé de mon mobile


-------- Message d'origine --------
De : marcbailly <notifications@github.com>
Date : 19/10/2015 08:57 (GMT+01:00)
À : android-rcs/rcsjta <rcsjta@noreply.github.com>
Objet : [rcsjta] [RI] Evolution for multimedia streaming session test (#171)


With the current implementation of the RI for the multimedia streaming session, the users needs to press several times the send button on both devices to make the test work. And if the button is only pressed on only one of the devices, this is not working when devices are behind a NAT (which is often the case). This is due to some NAT traversal meschanismes for UDP packet ensured at the IMS level where the network needs to received at least one packet from the device to reuse the opened binding to be able to route RTP data to the device.
An interesting evolution would be to update the RI to automatically send RTP packet: one packet per seconds for example. This would be really more simple with that to test this feature.
(note: this point was discussed with Philippe).
thx

Marc

—
Reply to this email directly or view it on GitHub<https://github.com/android-rcs/rcsjta/issues/171>.

_________________________________________________________________________________________________________________________

Ce message et ses pieces jointes peuvent contenir des informations confidentielles ou privilegiees et ne doivent donc
pas etre diffuses, exploites ou copies sans autorisation. Si vous avez recu ce message par erreur, veuillez le signaler
a l'expediteur et le detruire ainsi que les pieces jointes. Les messages electroniques etant susceptibles d'alteration,
Orange decline toute responsabilite si ce message a ete altere, deforme ou falsifie. Merci.

This message and its attachments may contain confidential or privileged information that may be protected by law;
they should not be distributed, used or copied without authorisation.
If you have received this email in error, please notify the sender and delete this message and its attachments.
As emails may be altered, Orange is not liable for messages that have been modified, changed or falsified.
Thank you.

**Comment by marcbailly** [comment]
as discussed with Jean Marc, the proposal is to have the RI that automatically start sending RTP packets (1 per second for example) and to chanbge the button into a "stop streaming/restart streaming"

**Comment by yplo6403** [comment]
Evolution implemented with commit:
commit 988c4f773c2d32f2a2b84915ac755e4218a96cd3
Author: yplo6403 <philippe.lemordant@orange.com>
Date:   Thu Oct 29 16:40:57 2015 +0100

    Fixes issue 171: [RI] Evolution for multimedia streaming session test

    - RI periodically sends RTP packets (1 per second)
    - Change the button "Send data" into a "stop RTP streaming/start RTP streaming" button
