### ISSUE TITLE
HTTP(S) based client configuration mechanism does not support/implement GBA Authentication

### ISSUE THREAD

**Issue by lgxace** [android-rcs/rcsjta#202]
Dear friends,

from the stack we can see that our rcs provisioning implement does not support GBA Authentication.

Could you kindly help me ?

I am eager to get your reply.

For GBA related procedures, refer to RCC.14

2.4 HTTP(S) based client configuration mechanism with GBA Authentication

Thanks & Regards,
Ace Guangxiang

**Comment by lgxace** [comment]
Dears any result ?

**Comment by yplo6403** [comment]
I used to work on GBA a long time ago. Support of GBA in the CMS is an option of the standard and there is not requirement from Orange to implement this authentication currently. We (Orange) cannot develop this authentication because we don't have the BSF and NAF equipments on our integration platform to test the feature. Moreover I was told that even with Android Marshmallow, it is still not possible for carriers (at least for Orange) to have a secured access to the SIM API.
